name: PartyChat
version: 1.0.0
main: cycle00.partychat.PartyChat
api-version: 1.16
author: Cycle00
commands:
  party:
    description: Party management commands.
    aliases: [p]
  partychat:
    description: Toggle between chats.
    aliases: [pchat, pc]
  globalchat:
    description: Send messages in normal chat
    aliases: [gchat, gc]